### ISSUE TITLE
Empty Calendar causes calendar to explode

### ISSUE THREAD

**Issue by Typel** [thenly/all-in-one-event-calendar#1218]
Monthly view calendars ( example: [ai1ec cat_name="Events" view="monthly"] ) explode if there are no events for the current month. The problem isn't CSS related - rather, the source code reveals that the calendar gets littered with empty `<p>` and `<br>` tags throughout.

I've actually already found a solution for this, but working up through the support channels didn't lead anywhere so I'm letting you guys know over here so we hopefully don't have to keep patching it manually every time there is an update. Here's the fix:

/app/view/calendar/shortcode.php
Add this line right before $page_content['html'] gets returned:
`$page_content['html'] = preg_replace( '/\s+/', ' ', $page_content['html'] );`

Thanks - hope this helps.

**Comment by Typel** [comment]
Found this same bug in the widget view as well as the shortcode view. I'm guessing the problem is in /app/view/calendar/widget.php but I haven't found a fix for that one yet.

**Comment by Typel** [comment]
Does anybody else experience this problem? I have this plugin installed on over 10 sites using a variety of different mainstream themes and every single one of them must be manually patched or else this plugin blows up with br and p tags and ends up looking terrible. Lately it happens even if there _are_ events in a particular view. I provided a fix for one of the views more than 4 months ago - when can we see some movement? Is anybody watching this project?

**Comment by uchu** [comment]
Hey @Typel 
Thank you for raising issue this again, it was somehow lost. We'll include the fix in the upcoming release.
Sorry for the delay.
Pavel.

**Comment by calvin-yeh** [comment]
Fixed. Will be available in the next release (2.5.20).
