### ISSUE TITLE
Ai1ec_Event_Search->get_events_between() causes excessively large queries

### ISSUE THREAD

**Issue by zrothauser** [thenly/all-in-one-event-calendar#1222]
When querying a wide range of dates, with many repeating dates, the call to update_meta_cache() in `get_events_between()` can become very long, as post IDs are duplicated for each time an event is repeated. 

On some hosts, this query may be killed.

**Comment by halfempty** [comment]
Yes, I'm also experiencing this issue.

**Comment by calvin-yeh** [comment]
Thanks! PR merged and the code will be available in the next release (2.5.17)
